# Eat Safe, Love

## Notebook Set Up

In [1]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database
print(mongo.list_database_names())

['admin', 'config', 'local', 'met', 'petsitly_marketing', 'uk_food']

In [5]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [6]:
# Find the establishments with a hygiene score of 20
query = {"scores.Hygiene":20}
results = establishments.find(query)

# Use count_documents to display the number of documents in the result
print(f'Number of documents with Hygiene Score of 20: {establishments.count_documents(query)}')

# Display the first document in the results using pprint
print('First Document:')
pprint(results[0])

Number of documents with Hygiene Score of 20: 41
First Document:
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64fa75a594f0d71905e3205f'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [7]:
# Convert the result to a Pandas DataFrame
import pandas as pd
hygiene_df = pd.json_normalize(results)

# Display the number of rows in the DataFrame
print(f'Number of rows: {len(hygiene_df)}')

# Display the first 10 rows of the DataFrame
hygiene_df.head(10)

Number of rows: 41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,64fa75a594f0d71905e3205f,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,0.276940,50.769705,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,64fa75a594f0d71905e323dd,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,1.278721,51.857536,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,64fa75a594f0d71905e326eb,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,1.159270,51.789429,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,64fa75a594f0d71905e328d7,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,0.102020,50.770885,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,64fa75a594f0d71905e328e9,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,0.101446,50.770724,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,64fa75a594f0d71905e33284,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,0.736349,51.541448,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,64fa75a594f0d71905e334a6,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,0.712167,51.535007,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,64fa75a594f0d71905e349ce,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,0.602364,51.591515,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,64fa75a594f0d71905e34e15,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,0.146450,51.185947,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,64fa75a594f0d71905e3562b,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,0.462307,51.570050,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [8]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query_2 = {"LocalAuthorityName": {'$regex':"London"}, "RatingValue":{'$gte': 4}}
results_2 = establishments.find(query)

# Use count_documents to display the number of documents in the result
print(f'Number of documents: {establishments.count_documents(query)}')

# Display the first document in the results using pprint
print('First Document:')
pprint(results_2[0])

Number of documents: 41
First Document:
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64fa75a594f0d71905e3205f'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [9]:
# Convert the result to a Pandas DataFrame
london_df = pd.json_normalize(results_2)

# Display the number of rows in the DataFrame
print(f'Number of rows: {len(london_df)}')

# Display the first 10 rows of the DataFrame
london_df.head(10)

Number of rows: 41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,64fa75a594f0d71905e3205f,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,0.276940,50.769705,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,64fa75a594f0d71905e323dd,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,1.278721,51.857536,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,64fa75a594f0d71905e326eb,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,1.159270,51.789429,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,64fa75a594f0d71905e328d7,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,0.102020,50.770885,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,64fa75a594f0d71905e328e9,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,0.101446,50.770724,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,64fa75a594f0d71905e33284,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,0.736349,51.541448,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,64fa75a594f0d71905e334a6,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,0.712167,51.535007,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,64fa75a594f0d71905e349ce,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,0.602364,51.591515,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,64fa75a594f0d71905e34e15,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,0.146450,51.185947,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,64fa75a594f0d71905e3562b,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,0.462307,51.570050,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [10]:
# Search within 0.01 degree on either side of the latitude and longitude.
degree_search = 0.01
document = list(establishments.find({'BusinessName': 'Penang Flavours'}))
latitude = document[0]['geocode']['latitude']
longitude = document[0]['geocode']['longitude']

# Rating value must equal 5
query_3 = {
    'RatingValue': 5,
    'geocode.latitude': {
        '$gte': latitude - degree_search,
        '$lte': latitude + degree_search},
    'geocode.longitude': {
        '$gte': longitude - degree_search,
        '$lte': longitude + degree_search}
}

# Sort by hygiene score
sort = [('scores.Hygiene', 1)]
results_3 = list(establishments.find(query).sort(sort))

# Print the results
pprint(results_3[0:5])

[{'AddressLine1': '5-6 Southfields Road',
  'AddressLine2': 'Eastbourne',
  'AddressLine3': 'East Sussex',
  'AddressLine4': '',
  'BusinessName': 'The Chase Rest Home',
  'BusinessType': 'Caring Premises',
  'BusinessTypeID': 5,
  'ChangesByServerID': 0,
  'Distance': 4613.888288172291,
  'FHRSID': 110681,
  'LocalAuthorityBusinessID': '4029',
  'LocalAuthorityCode': '102',
  'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
  'LocalAuthorityName': 'Eastbourne',
  'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'BN21 1BU',
  'RatingDate': '2021-09-23T00:00:00',
  'RatingKey': 'fhrs_0_en-gb',
  'RatingValue': 0,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64fa75a594f0d71905e3205f'),
  'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}},
 {'AddressLine1': 'Hall Lane',
  'AddressLine2': 'Walton-on-the-Naze',
  'AddressLine3': 'Essex',
  'AddressLine4': '',
  'BusinessName': 'Brenalwood',
  'BusinessType': 'Caring Premises',
  'BusinessTypeID': 5,
  'ChangesByServerID': 0,
  'Distance': 4617.965823673803,
  'FHRSID': 612039,
  'LocalAuthorityBusinessID': '1970/FOOD',
  'LocalAuthorityCode': '120',
  'LocalAuthorityEmailAddress': 'fhsadmin@tendringdc.gov.uk',
  'LocalAuthorityName': 'Tendring',
  'LocalAuthorityWebSite': 'http://www.tendringdc.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'CO14 8HN',
  'RatingDate': '2022-06-22T00:00:00',
  'RatingKey': 'fhrs_0_en-gb',
  'RatingValue': 0,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64fa75a594f0d71905e323dd'),
  'geocode': {'latitude': 51.857536, 'longitude': 1.278721},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/612039',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 30, 'Hygiene': 20, 'Structural': 15}},
 {'AddressLine1': '53 Marine Parade East',
  'AddressLine2': 'Clacton On Sea',
  'AddressLine3': 'Essex',
  'AddressLine4': '',
  'BusinessName': 'Melrose Hotel',
  'BusinessType': 'Hotel/bed & breakfast/guest house',
  'BusinessTypeID': 7842,
  'ChangesByServerID': 0,
  'Distance': 4619.6561440278165,
  'FHRSID': 730933,
  'LocalAuthorityBusinessID': '1698/FOOD',
  'LocalAuthorityCode': '120',
  'LocalAuthorityEmailAddress': 'fhsadmin@tendringdc.gov.uk',
  'LocalAuthorityName': 'Tendring',
  'LocalAuthorityWebSite': 'http://www.tendringdc.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'CO15 6AD',
  'RatingDate': '2021-08-13T00:00:00',
  'RatingKey': 'fhrs_0_en-gb',
  'RatingValue': 0,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64fa75a594f0d71905e326eb'),
  'geocode': {'latitude': 51.789429, 'longitude': 1.15927},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/730933',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}},
 {'AddressLine1': '4 High Street',
  'AddressLine2': 'Seaford',
  'AddressLine3': 'East Sussex',
  'AddressLine4': '',
  'BusinessName': 'Seaford Pizza',
  'BusinessType': 'Takeaway/sandwich shop',
  'BusinessTypeID': 7844,
  'ChangesByServerID': 0,
  'Distance': 4620.421724673841,
  'FHRSID': 172735,
  'LocalAuthorityBusinessID': 'PI/000023858',
  'LocalAuthorityCode': '105',
  'LocalAuthorityEmailAddress': 'ehealth.ldc@lewes-eastbourne.gov.uk',
  'LocalAuthorityName': 'Lewes',
  'LocalAuthorityWebSite': 'http://www.lewes-eastbourne.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'BN25 1PG',
  'RatingDate': '2021-12-23T00:00:00',
  'RatingKey': 'fhrs_1_en-gb',
  'RatingValue': 1,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64fa75a594f0d71905e328d7'),
  'geocode': {'latitude': 50.770885, 'longitude': 0.10202},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/172735',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 10}},
 {'AddressLine1': '5 South Street',
  'AddressLine2': 'Seaford',
  'AddressLine3': 'East Sussex',
  'AddressLine4': '',
  'BusinessName': 'Golden Palace',
  'BusinessType': 'Restaurant/Cafe/Canteen',
  'BusinessTypeID': 1,
  'ChangesByServerID': 0,
  'Distance': 4620.437179097401,
  'FHRSID': 172953,
  'LocalAuthorityBusinessID': 'PI/000024532',
  'LocalAuthorityCode': '105',
  'LocalAuthorityEmailAddress': 'ehealth.ldc@lewes-eastbourne.gov.uk',
  'LocalAuthorityName': 'Lewes',
  'LocalAuthorityWebSite': 'http://www.lewes-eastbourne.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'BN25 1HP',
  'RatingDate': '2021-10-07T00:00:00',
  'RatingKey': 'fhrs_1_en-gb',
  'RatingValue': 1,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64fa75a594f0d71905e328e9'),
  'geocode': {'latitude': 50.770724, 'longitude': 0.101446},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/172953',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 10}}]

In [11]:
# Convert result to Pandas DataFrame
penang_flav_df = pd.json_normalize(results_3)

penang_flav_df.head(5)

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,64fa75a594f0d71905e3205f,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,0.276940,50.769705,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,64fa75a594f0d71905e323dd,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,1.278721,51.857536,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,64fa75a594f0d71905e326eb,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,1.159270,51.789429,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,64fa75a594f0d71905e328d7,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,0.102020,50.770885,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,64fa75a594f0d71905e328e9,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,0.101446,50.770724,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [12]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
match_query = {'$match': {'scores.Hygiene': 0}}

# 2. Groups the matches by Local Authority
group_query = {'$group': {'_id': "$LocalAuthorityName", 
                          'count': { '$sum': 1 }}
              }

# 3. Sorts the matches from highest to lowest
sort_values = {'$sort': {'count': -1, '_id': 1 }}

# Print the number of documents in the result
pipeline = [match_query, group_query, sort_values]
results_4 = list(establishments.aggregate(pipeline))
print(f'Number of documents: {len(results_4)}')

# Print the first 10 results
pprint(results_4[0:10])

Number of documents: 55
[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [13]:
# Convert the result to a Pandas DataFrame
local_df = pd.json_normalize(results_4)

# Display the number of rows in the DataFrame
print(f'Number of rows: {len(local_df)}')

# Display the first 10 rows of the DataFrame
local_df.head(10)

Number of rows: 55

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542